# Generated by Django 4.2.17 on 2025-01-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tests', '0002_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='error_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='method',
            field=models.CharField(default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='testcase',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='request_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
