# Generated by Django 5.1.4 on 2025-01-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tests', '0004_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
