# Generated by Django 5.1.4 on 2025-01-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tests', '0002_auto_add_test_case_to_test_result'),
        ('api_tests', '0006_alter_testresult_owner'),
    ]

    operations = [
    ]
