# Generated by Django 5.1.4 on 2025-01-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tests', '0007_merge_20250108_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='status',
            field=models.CharField(default='new', max_length=50),
        ),
    ]
