# Generated by Django 5.1.4 on 2025-01-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tests', '0008_testcase_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
