# Generated by Django 5.1.4 on 2025-01-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tests', '0009_baseurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
