apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-django
  namespace: ai-testops
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - ai-testops
    labelSelectors:
      app: django-app
  scheduler:
    cron: "@every 5m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-consumer
  namespace: ai-testops
spec:
  action: pod-kill
  mode: fixed
  value: "1"
  duration: "20s"
  selector:
    namespaces:
      - ai-testops
    labelSelectors:
      app: test-execute-consumer
  scheduler:
    cron: "@every 3m"
