apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-testops-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: wide
  
  source:
    repoURL: https://huynhduc0.github.io/ai-testops
    chart: testops-infra
    targetRevision: "1.*.*"
    helm:
      values: |
        # Enable only Postgres
        postgres:
          enabled: true
        kafka:
          enabled: false
        ingress:
          enabled: false
        rbac:
          enabled: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: testops
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SyncTimeout=1200
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 20m
