apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-testops-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  
  source:
    repoURL: https://huynhduc0.github.io/ai-testops
    chart: ai-testops
    targetRevision: "1.0.*"
    helm:
      values: |
        # Enable only Postgres
        postgres:
          enabled: true
        kafka:
          enabled: false
        djangoApp:
          enabled: false
        consumer:
          enabled: false
        kafkaUI:
          enabled: false
        ingress:
          enabled: false
        keda:
          enabled: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: testops
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
